name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [arm64, amd64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'
        
    - name: Build for Windows
      if: ${{ matrix.os }} == "windows latest" && ${{ matrix.arch }} != "arm64"
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }} 
      run: |
          go build -v -o ${{ matrix.os }}-${{ matrix.arch }}.exe
      shell: pwsh

    - name: Build for Linux
      if: ${{ matrix.os }} == "ubuntu-latest"
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
      run: |
        go build -v -o ${{ matrix.os }}-${{ matrix.arch }}
      shell: bash
        
    - name: Zip for Windows
      if: ${{ matrix.os }} == "windows-latest" && ${{ matrix.arch }} != "arm64"
      run: |
        7z a -r ${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}.exe
      shell: pwsh

    - name: Zip for Linux
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: |
        zip -r ${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}
      shell: bash

    - name: Upload Linux artifact
      if: ${{ matrix.os }} == "windows-latest" && ${{ matrix.arch }} != "arm64"
      uses: actions/upload-artifact@v4
      with:
        name: scrap-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ matrix.os }}-${{ matrix.arch }}.zip
        
    - name: Upload Windows artifact
      if: ${{ matrix.os }} == "ubuntu-latest" 
      uses: actions/upload-artifact@v4
      with:
        name: scrap-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ matrix.os }}-${{ matrix.arch }}.zip
      
