name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        arch: [arm64, amd64]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'
        
    - name: Build Windows
      env:
        GOOS: windows
        GOARCH: ${{ matrix.arch }}
      if: ${{ matrix.os }} == "windows latest" && ${{ matrix.arch}} != "arm64"
      run: |
          go build -v -o ${{ matrix.os }}-${{ matrix.arch }}.exe
      shell: pwsh

    - name: Build Linux
      env:
        GOOS: linux
        GOARCH: ${{ matrix.arch }}
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: |
        go build -v -o ${{ matrix.os }}-${{ matrix.arch }}
      shell: bash
        
    - name: Zip Windows
      if: ${{ matrix.os }} == "windows-latest"
      run: |
        7z a -r ${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}.exe
      shell: pwsh

    - name: Zip Linux
      if: ${{ matrix.os }} == "ubuntu-latest"
      run: |
        zip -r ${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-artifact-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ matrix.os }}-${{ matrix.arch }}.zip
