name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [arm64, amd64]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'
        
    - name: Build arm64
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build -v -o ${{ matrix.os }}-${{ matrix.arch }}


    - name: Zip
      run: zip -r ${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-artifact-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ matrix.os }}-${{ matrix.arch }}.zip
