name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Install
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
        GOBIN: ${{ github.workspace }}/bin/${{ matrix.os }}-${{ matrix.arch }}
      run: go install -v ./...

    - name: Zip
      run: zip -r bin/${{ matrix.os }}-${{ matrix.arch }}.zip bin/${{ matrix.os }}-${{ matrix.arch }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: go-artifact-${{ matrix.os }}-${{ matrix.arch }}
        path: bin/${{ matrix.os }}-${{ matrix.arch }}.zip
