name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, android]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
          - os: android
            arch: amd64
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'
      - name: Build
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            go build -ldflags="-w -s" -o scrap.exe main.go
          else
            go build -ldflags="-w -s" -o scrap main.go
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: scrap-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            if [ "${{ matrix.os }}" = "windows" ]; then
              scrap.exe
            else
              scrap
            fi

