name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.6'

    - name: Build arm64
      env:
        GOOS: linux
        GOARCH: arm64
      run: go build -v -o bin/linux-arm64 ./...


    - name: Zip
      run: zip -r bin/${{ matrix.os }}-${{ matrix.arch }}.zip bin/${{ matrix.os }}-${{ matrix.arch }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: go-artifact-${{ matrix.os }}-${{ matrix.arch }}
        path: bin/${{ matrix.os }}-${{ matrix.arch }}.zip
