name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, android]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
          - os: android
            arch: amd64
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.6'

      - name: Setup Tinygo
        run: |
          sudo apt-get install wget
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.31.1/tinygo_0.31.1_amd64.deb
          sudo dpkg -i tinygo_0.31.1_amd64.deb
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          if [ "${{ matrix.os }}" = "windows" ]; then
            tinygo build -o scrap.exe main.go
          else
            tinygo build -o scrap main.go
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: scrap-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            if [ "${{ matrix.os }}" = "windows" ]; then
              scrap.exe
            else
              scrap
            fi

