name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, android]
        arch: [arm64, amd64, arm]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'
        
    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build -v -o scrap

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: scrap-${{ matrix.os }}-${{ matrix.arch }}
        path: scrap
