name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [linux, windows-latest]
        arch: [arm64, amd64]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.21.6'
        
    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          go build -v -o ${{ matrix.os }}-${{ matrix.arch }}.exe
        } else {
          go build -v -o ${{ matrix.os }}-${{ matrix.arch }}
        }
      shell: pwsh
        
    - name: Zip
      run: |
        if ("${{ matrix.os }}" -eq "windows-latest") {
          7z a -r ${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}.exe
        } else {
          zip -r ${{ matrix.os }}-${{ matrix.arch }}.zip ${{ matrix.os }}-${{ matrix.arch }}
        }
      shell: pwsh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-artifact-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ matrix.os }}-${{ matrix.arch }}.zip
